keys:
  - &admin_begad 49F7C69C772788520405E5563F4E6199EB40BC75
  - &server_home_pc age1ul93temcp2k6gx9g9m4kcklvxl9jyc38hhnr780arsn2q808947s703m72
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *admin_begad
        age:
          - *server_home_pc
