vikunja_resend_api_key: ENC[AES256_GCM,data:yDlcVPFi0GO1G+cQodznAgOEO7ZpEqJnsN8J8OSTLHr5TnlJ,iv:OQ4JxYwne0rQytvHaym8iySdrVIhDBhHaLusSXmW73A=,tag:77/A/GMu5YVCuQE/gTqxgA==,type:str]
sops:
    age:
        - recipient: age18s7ft6tzregszuzpqnhzp55nxdpwm9t6xrn0k334dc927sxj5ajq2ywnyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZytJeTd2d3kyZFpHS2Fl
            Tjc5dDF0ejhubGJEaCs0V1Z1L0k5UDNwNXpFCkUyTWoxR1FCMkJlZ2dhc0xaTEh6
            NUFnL2NkK2RuTGowSEhQRU5sRmM1WDQKLS0tIE0zTTlVOC94RGQyamJtbEt5VzRB
            SGd5cFpWOWEwSEpZNFpyTUwwWUxQTG8KuzXCjWjyrTEojTMDT/Sv0ymQSUJBfqYG
            pAsHpbqonDSbApqXXUxTNDws29w0lSODYTT5wOOUqnqe+zWLbnX/3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-30T12:58:14Z"
    mac: ENC[AES256_GCM,data:0hXh9ZhG3tf3gaicSqon7W3+cnjV9MMXpaVom5FUzDAHa7ktWtbK0oWkiBXTyQnIBHm5J/lvEIJNoehZErbpV4uSMBST+7SkR+fKyvObz6XiafgRqZ8lxQRRyZNMS/ywJG5+kVDrucxJ6kXlnnGi2yXU4YhB+DsPZbCIPFO16/g=,iv:pX1bbVEHIvuhDmpfJGvGZpuVCxqqiHXByQva1ZBeT9o=,tag:42QX/YNlP3WUk4hbuzgRRg==,type:str]
    pgp:
        - created_at: "2026-01-25T20:54:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HvlJi0RQHSARAAtEKSsF5w31rm7+clXehmAgQk/w+p9NSJuMSm/XzKhlLw
            CwU+yTqKsq3UKjh7gKGqq7WUta2Nc7ubfxWMorWjzg4qjwV56TmIrw6pIqn6Z3aU
            bkRK5wEkMu0Kd22qE+hpwqBMSzc17dR6U4Q4ZX8FT1W3Q3+OpWdIVzipUhIJs6z2
            2MLTUtEvy5wj73PfI6bDxebDRhYsFk5+eT3MAbE8CHmGDdih5XYhq91MbIKLgvsf
            ioi1A4GZhpNfF5Cee3jEjQRJEseWG9PChvsY8EPc7c8wIUkMVrsmHZRgKbyiK3h6
            ZjzQBFsX7+da1nJe8k12gQGbYAFPmsZg/L27xpIOGdGrdjZBatCIq+NOt9X1xk1b
            oKr1z9raNugUqVDOsVqGCWBnE+AQ88GlbdQdJyqjfpdKqCw2OwlEDuVsgzWnfZh3
            e9lsiMmtDccuRgiepy4oA1Yjn4BzIcH/b/hhAmQJFW3BMtStqq4/QQ9V+7GzDy/q
            LMOR9Lr++L/emmKAjireMtZWjsw0QNJHUg9EdffLhpv08i5FlaWCEDbPqxOKib4m
            8hCRQXLnfesaquf6d2iQZtehWUVT8XplQ4WzfDhUBeg6nOjmYavnVhu3Gk1JN5+Y
            ARgEDmsVb/klik4pP+uVCM8I2AMQNHGybPcDcoDbxLyR/JMMgdBFxA57Ig1ZgPnS
            XAEvoWe9D6x7m+d7kVA0jy7GTheAZChoqxo9QMc2mG23SfvdHLuh5tsvgcQR6J4K
            UD3zSGTSGV211km22SpJ9Y1dYVjzY+m2MbBcpkmbnD4JRShRBYKQNy/Kzltt
            =9iw0
            -----END PGP MESSAGE-----
          fp: 49F7C69C772788520405E5563F4E6199EB40BC75
    unencrypted_suffix: _unencrypted
    version: 3.10.2
