secret: ENC[AES256_GCM,data:nYeAVPS8aJH+tmxLfg==,iv:eYDQDjR2n5y4KzyLPHX8pRQ0nmYmTnW6rzshW2hQQVA=,tag:yPzSTVUX24JdcIjByVzNig==,type:str]
sops:
    age:
        - recipient: age1ul93temcp2k6gx9g9m4kcklvxl9jyc38hhnr780arsn2q808947s703m72
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RThONWRUaXdXL1QvZ0Rs
            RVVQcGoxRzZ3U3ZaSFQxK3k2MCs3TlU4WDN3CngzMnhvTXN1ek10WHp3NnpEbFdO
            YVc4aFc1VTR5cDdtZDBDa3RiN1dOZ3MKLS0tIGpWdXlyRzgvWjczcmsxWkltOWFT
            VjRwNzROUG96cDBWRnZWald3NzZIelEKJnKeh6GwkvkYZLhKTf5MB+qrWlNeex6f
            W0dkhjHEAauvWnNa2IklNZl+CDQggRzj0cW6WNtYkcHlI5sjiYLLww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-21T08:48:27Z"
    mac: ENC[AES256_GCM,data:We01EpCNKxo6wEx434Q0zVvQi0mxjnUS5SaxehZOWgOdzZ+glYllzPxTzQzexsfD53a4bTV+XqC//S8Li4VITL+GjH078RVpldOj02hTAqJJZGF/N1von9FlF/fU9BqfqW7No/4eJ/02w+CcMXcBoMhsXiRdmSEsUCVsTb1usjE=,iv:IeQW/yIEGs9UQ0Hz3nH5P5jkoSBmvRlMNRB1tRhuMGg=,tag:6T1i07giR3VD5EYDHFCv7w==,type:str]
    pgp:
        - created_at: "2025-04-21T08:48:17Z"
          enc: "-----BEGIN PGP MESSAGE-----\r\n\r\nhQIMA0HvlJi0RQHSARAAyUoo2pBkDlbceVwI5bAZv5B3r1r6pLzgGO/Y9bjprlo4\r\nWlgHedDOKITg5xG9fomhwplfDmKnRrTvRg6XQUwBJ+/OqmP/hF4xYNNPVrMWlqE4\r\nxrnvrsfdsY0cOgdfkC2fm/Saaz0wNOWdhRyldab8SD+VwTiuxJHs9yaSp/D9oA0O\r\nGJ+TgfiYA1q4c+E3QMZlSQh24n5wbga1+VgdW1M3he+xesUXDmrWsfdgNeu9glZV\r\nVheCdyAZZ00Fd66vOXtE/W8BH7bDBLmxEVMRjIhZ5RI06TswlAJRR54mtS34IflO\r\nyFKJKsArpI19P4+bge6RGLScGpymVF2hpB14Wh+IpMJoNyrT+S5qK+QfI36IOwPY\r\nHxZ+rpYs7lCHm64Nyf06dNZ9/6/Zl4SPj0wUE9e66nb/iDDDiApooZydhIQO5ydr\r\nLx3eTYT4rNRL76OTQ58JDWROJvoMx/ZRCCfCRrvgxeaoG4zeoaodrhK0zUXoqU8e\r\n9r8g2Yx7t30WS3edKpVK+HlZSDJo+ycE3QMiR9kOTgJ//nSNLtHfN89TzQ3yGIUR\r\nCrPEJJBKRpxhIR/Iz6TvcmiDRyxUhV6LljXwYtvB8r1ReMWadUrvjeakWC2ITaK8\r\nEZOMiO4gdRM1GLcJI8kXrh2Zor1b9f+aycZn3SDCSvBqLQmxzRoWyt5qXBlzQiDU\r\nZgEJAhCdbX3rZNlbB0DZ5VqfS8YpTLt9BBD3LyBI0Z0fF1lFLwYaCEb+mHTCJkwQ\r\nJOzRPGPv6vD0Tj8Sf1DyCKXsmcEEdiJpuFNr8TT0meg53G12wAuZesIg96eC2axm\r\neHGcFIeO6Q==\r\n=1rFY\r\n-----END PGP MESSAGE-----"
          fp: 49F7C69C772788520405E5563F4E6199EB40BC75
    unencrypted_suffix: _unencrypted
    version: 3.10.2
