vikunja_resend_api_key: ENC[AES256_GCM,data:yDlcVPFi0GO1G+cQodznAgOEO7ZpEqJnsN8J8OSTLHr5TnlJ,iv:OQ4JxYwne0rQytvHaym8iySdrVIhDBhHaLusSXmW73A=,tag:77/A/GMu5YVCuQE/gTqxgA==,type:str]
sops:
    lastmodified: "2025-04-30T12:58:14Z"
    mac: ENC[AES256_GCM,data:0hXh9ZhG3tf3gaicSqon7W3+cnjV9MMXpaVom5FUzDAHa7ktWtbK0oWkiBXTyQnIBHm5J/lvEIJNoehZErbpV4uSMBST+7SkR+fKyvObz6XiafgRqZ8lxQRRyZNMS/ywJG5+kVDrucxJ6kXlnnGi2yXU4YhB+DsPZbCIPFO16/g=,iv:pX1bbVEHIvuhDmpfJGvGZpuVCxqqiHXByQva1ZBeT9o=,tag:42QX/YNlP3WUk4hbuzgRRg==,type:str]
    pgp:
        - created_at: "2026-01-25T14:05:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HvlJi0RQHSAQ//Ub4kuWsGb9l9QL/3+Ma+JYUuud0HA6lWLynD+kDKDa4v
            7KgGy1q5da4Pl3rNYmHNKWzju/Jbw2Vr7kimZz9Gvr4Ogv3B2K3nXjdqb7gxrliw
            nCUFQhtjMp7OVHGUkD+3DHq9XtOCLVCqO0LYx6sisijHXdYKjF9gBKvkIZpvCyUg
            b6rpIo+u5xj2qxGC8WhNvIs2ZkcQfTp2Vbs/QVF7vMbQ2NOHydfHzByhTQfS31w8
            19JKhR9yDqDVnDXWSHn+vtL9tcY1NgdmMHY93R+ossSV42NN0OyVFgeCFki4zhXd
            4fFt7v0kpnySzvaE9X11tDbuLW6xmk9ANtIvBftOfmx5JHZRui66TyzaZrWJg8Ua
            wMNF/Cea4eWZUX88geq6I3s6dqU5O8XGoIY5Ito2k+Z2MNu5SAILARd3mGUGmuiq
            L9e3sifJ08FnXj1Ke40NirLvn7tAPhjJqfiz6n/AkqpsEb/WdBy27EPI9R+u0PM9
            is1TQ2uQ3rhU0xmx0rEL7PT1hyFJVAhG7KOZ3eldxyJ93QuAVM3LIJP2wf43TlxS
            4ZI/yuJc/CNvoe8K91SFqNyK61akiN57dYd3cJQtk2GCh4sagzP6/EaEEYjcN/+p
            mPrCRz5r2VWstMUzDXMI3QAJixYSeJOaoWcnpKmHlUPDZ4DFduU7SVV+sjDlCljS
            XAH7lYwLxjYE4WCLdO+C0L+X3ycJGzMFkiWIaTz9DAqD9UOR/D82/eq/ddAhjLq5
            IXOnjNqTVdHJU98DjXBLQfHjRejST1bKxnPjkIo5HMf/YEFPIghC9UqulmtP
            =g9gV
            -----END PGP MESSAGE-----
          fp: 49F7C69C772788520405E5563F4E6199EB40BC75
    unencrypted_suffix: _unencrypted
    version: 3.10.2
