vikunja_resend_api_key: ENC[AES256_GCM,data:yDlcVPFi0GO1G+cQodznAgOEO7ZpEqJnsN8J8OSTLHr5TnlJ,iv:OQ4JxYwne0rQytvHaym8iySdrVIhDBhHaLusSXmW73A=,tag:77/A/GMu5YVCuQE/gTqxgA==,type:str]
wg_vps_hashed_password: ENC[AES256_GCM,data:AAr8Gy5QGL29YQt/8fIJE3hJWeakLGWWDCDNIj5RXt0jMPrX2uOfAXwiIPPuCPDeD+yuDgPoHC2M3XJUt+E7O+DgV5TM30zcdw==,iv:FnxR2kcarqVurOx829HCkg68J1rQJ6Fp9FY/LMvXcFc=,tag:fwiky5ZMXICFXRk2CAsX6A==,type:str]
sops:
    age:
        - recipient: age18s7ft6tzregszuzpqnhzp55nxdpwm9t6xrn0k334dc927sxj5ajq2ywnyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TlJ6eG5yWGkxYjV0WWkr
            QWduWllJVC9DdkRmaCtYZnlmNFJkektXS1M0CllNK1lPajVrUGU4cDh1OWhJUU1a
            aVJMd1FyUENGcG5lRlMrODViOW4yREEKLS0tIGFXQVl4R3lzczJLRThkN1BmRjMv
            bGhMbTFSTVkxQ0pyZWdlTGhOdExkcDAKTlxjcROtwmlUFiS4RHERVX6XsmHzcAeZ
            vSEn5iaOrJa2uwiA4A5bo30DxRP/Mlw8FBo7e2iy+hjelCiWDid9LQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age148tm8a7hpjcfgfaz7n33gtz5xhl6d0spzgzw603almyafr5hdqksue8yx5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTXJuWHF2bUdnaXhCYWNZ
            NUFtNkZ1VFhWRDZxU1RPaVo2eFVCTjlPT2swCk9pSnJKYjlYQVU2Z3k3ZGpNbzZH
            ZDlQTGlwcUMydTBzQTNiT1pVWWo4d28KLS0tIGJOdEZvYkxmbUlnUkpaNm16ZlZD
            UUgxK1RrRDBROVBaQjE0Q0w5U1ZWY2cKwvuKCU8S/IvyGZxhnbZXJzSTp56S9yxT
            VgmCrVX6kvF5Sb+0LP/cqxEVanlTtr/1FG3q9I+GG8EgvAg+DHw/qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T06:52:57Z"
    mac: ENC[AES256_GCM,data:W4AIq9olaxwg+ABmTGL3ur4UFskrj8N7fUQTRMvlc5K7MTnySDTdxGnPhaHid2vR1Mk8/JpDXgW4xYued8W81laHp+4z8c1pmiDTvYigBoq0WtMpGJ3aCl5101SYhWJ4zWMDSqj2Rm58Tx9UVq2mL3L3iZSPwrnLeGQxYDfynts=,iv:OIg8ulfVE7uRvgGwiHnW+hgSP6whB3UNjQXWGBpxIfo=,tag:Zye+ystNKa/m+vjQI0OIyg==,type:str]
    pgp:
        - created_at: "2026-06-01T16:24:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HvlJi0RQHSAQ//VedpRB7pvYNItU7er38T6OQXpJnAoyLP9KfpdtIxnl56
            KhJ1CqAQfrtoeGh3TrmWAi2ov+PT9KdeCjFo28iJekfhQqpXkA0PDDzxsHB1CvYx
            htx5VLjbd6iXFBYOS6s5kUv16bYfODJGkLqgfok7/rmdnYi6C1bbc/p1QHwZxUFb
            JAUDWt7o7JwmwnuV+51D3qyb7E5JXTDzeMOb7/AYAWBlHn+sBjmeVGIHnG2EvtPF
            /jdrV7qlNN/WY1+U4RF6JsUxmk/aRqIu0v1UYrn2qHmDJc3jamIFflXhVG1Gt4fF
            eL2hkc7LafqINAkAFos08xjCJLJJ5PFzqG8Lo4lgQKdGHKGDTZLTCbHcg8KI6Bso
            dQCQY4F9YWct2Jp3oJV7l7Qa0cjkgH+Feh7RARIfhY73d3QNvSC1bb/4Ji0rJgHZ
            NqbEPYmT/tAocTcZwTuEOCjKjQxmgxOCFeSg/HgOlfZLKNqAtgNhQmy1tfkRCt8N
            dMPlPs4+4KsHwnLeUv0eia4d9HxcIJgYpHj/Cs9h9ME7hZMDwgZHjYh4ic6U8OOu
            zjc4VAiVfRtYS+HUBj2IjbjT7poZ457g0lLhjl29oLkzHXXxa77Wy79KXHNIhYMi
            qQKc+zzB9aKSYoXPSwHGXu1NvYxYKCWWFefqzjIDWNZMVzXpN6TlS4DzSOaojtzS
            XAEARrzxpFVal4KO8J3t5hBMOAMDZ9hewFzZdm2u6B2HckqLiSQNh2Q5MaOgO6Yy
            4noIuVG3X9jZWFSqAfBh0PYHxszrlPNCOD1etGkNkQEXk8STixL8OXssGz2k
            =BKlQ
            -----END PGP MESSAGE-----
          fp: 49F7C69C772788520405E5563F4E6199EB40BC75
    unencrypted_suffix: _unencrypted
    version: 3.11.0
